# Generated by Django 6.0.2 on 2026-03-02 01:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskOp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='taskDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
